# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - "7.3"

global:
  - ADDITIONAL_CONFIG=config.travis.neon

env:
  - DEBUG_MODE=1

services:
  - mysql


install:
  - travis_retry composer install --no-progress --prefer-dist

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - mysql -e "create database IF NOT EXISTS paf_test;" -uroot
  - php bin/console app:database:init --drop-all-tables -d

script:
  - phpunit --configuration test/phpunit.xml --coverage-text

notifications:
  email:
   - "thoronir42@gmail.com"
