# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

branches:
  only:
    - master

php:
  - "7.4"
cache:
  - directories:
      - $HOME/.composer/cache/files

env:
  global:
    - CONFIG_FILE=config.travis.neon
    - DEBUG_MODE=1

install:
  - travis_retry composer install --no-progress --prefer-dist

jobs:
  include:
    - stage: "Quality Assurance"
      name: "PHP Code Sniffer"
      script: composer phpcs
    -
      name: "Tests"
      services:
        - mysql
      script:
        - mysql -e "create database IF NOT EXISTS paf_test;" -uroot
        - php bin/console app:database:init --drop-all-tables -d
        - composer test

notifications:
  email:
   - "thoronir42@gmail.com"
