<?php

namespace App\Controls\NavigationMenu;

use Nette\Application\UI;

/**
 * Class NavigationMenu
 * @package App\Controls\NavigationMenu
 *
 * @property		string $title
 * @property		string $brand_target
 */
class NavigationMenu extends UI\Control
{
	use NavigationMenuSubitems;

	protected $title;

	protected $brand_target;

	public function __construct()
	{
		parent::__construct();

		$this->title = 'Appliaction N';
		$this->brand_target = 'Default:';

	}

	/**
	 * @param string $title
	 */
	public function setTitle($title)
	{
		$this->title = $title;
	}

	public function setBrandAction($code)
	{
		$this->brand_target = $code;
	}

	public function link($destination, $args = array())
	{
		return $this->presenter->link($destination, $args); // TODO: Change the autogenerated stub
	}

	public function currentDropdown(NavMenuLink $item){
		/** @var NavMenuLink $subitem */
		foreach ($item->items as $subitem){
			if(!($subitem instanceof NavMenuLink)){
				continue;
			}

			if($subitem->getRole() == 'dropdown'){
				return $this->currentDropdown($subitem);
			}
			if($this->presenter->isLinkCurrent($item->target)){
				return true;
			}
		}
		return false;
	}


	public function renderTop(){
		$this->template->setFile(__DIR__ . "/topMenu.latte");

		$this->template->title = $this->title;
		$this->template->brand_code = $this->brand_target;
		$this->template->items = $this->items;

		$this->template->render();
	}
}

interface INavigationMenuFactory{

	/** @return NavigationMenu */
	public function create();
}
